name: Build and Push Docker Image

on:
  workflow_dispatch:
  repository_dispatch:
    types: [upstream-synced-and-merged]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match your Dockerfile's Node version
          cache: 'pnpm' # This sets up caching for pnpm, but doesn't install pnpm itself

      # --- NEW STEP: Manually install pnpm globally ---
      - name: Install pnpm globally
        run: |
          npm install -g pnpm@7.33.5 # Ensure this matches the version in your package.json / Dockerfile
        # No 'cache: pnpm' here, as actions/setup-node already handles it.

      - name: Regenerate pnpm-lock.yaml (if config mismatch)
        run: |
          echo "Checking pnpm lockfile configuration..."
          if ! pnpm install --frozen-lockfile; then
            echo "pnpm lockfile configuration mismatch detected. Regenerating lockfile..."
            pnpm install --no-frozen-lockfile
            if git diff --exit-code pnpm-lock.yaml; then
              echo "No changes to pnpm-lock.yaml after regeneration."
            else
              echo "pnpm-lock.yaml updated. Committing changes..."
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add pnpm-lock.yaml
              git commit -m "chore(pnpm): Auto-regenerate pnpm-lock.yaml for CI consistency [skip ci]"
              git push origin main
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stremify-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
