name: Build and Push Docker Image

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/stremify-app:latest .

      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/stremify-app:latest
