name: Sync Upstream Repository

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6:00 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote if it doesn't exist
        run: |
          git remote add upstream https://github.com/stremify/stremify.git || echo "Upstream remote already exists or cannot be added"

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Check for changes and merge
        id: merge_check
        run: |
          git checkout main
          # Check if upstream/main is ahead of main
          if git diff --quiet main upstream/main; then
            echo "No new changes detected in upstream/main. Main is already up-to-date or ahead."
            echo "merged=false" >> $GITHUB_OUTPUT
          else
            echo "New changes detected in upstream/main. Merging..."
            # Attempt to merge. --no-ff ensures a merge commit, even for fast-forwards.
            # This is generally preferred for clarity in history for sync actions.
            # If there are conflicts, this step will fail, and the workflow will stop.
            git merge --no-ff upstream/main
            echo "Merge completed."
            echo "merged=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes to fork
        # Only run this step if changes were actually merged
        if steps.merge_check.outputs.merged == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set the origin URL with the token for authentication
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/kiskey/stremify-docker.git
          git push origin main
          echo "Changes pushed to your fork."
