name: Sync Upstream Repository

on:
permissions:
contents: write
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8:00 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/stremify/stremify.git
          git fetch upstream

      - name: Merge upstream into main
        run: |
          git checkout main
          git merge upstream/main || echo "No changes to merge"

      - name: Check repository URL
        run: git remote -v

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/kiskey/stremify-docker.git
          git push origin main || echo "No changes to push"
